name: Build Book
on: [push, pull_request]
jobs:
  create-pdf:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew install pandoc
      - run: |
          brew install basictex
          eval "$(/usr/libexec/path_helper)"
      - run: |
          make
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: output/book.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: ebook
          path: output/book.epub

